[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About Me'
pageRef = '/about-me'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"